---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "Inventory/hosts.yaml"
    group_file: "Inventory/groups.yaml"
    defaults_file: "Inventory/defaults.yaml"
runner:
  plugin: threaded
  options:
    num_workers: 100
